/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as EnvironmentsRouteImport } from "./routes/environments";
import { Route as ProjectsRouteImport } from "./routes/projects";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: "/environments",
  path: "/environments",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectsRoute = ProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/environments": typeof EnvironmentsRoute;
  "/projects": typeof ProjectsRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/environments": typeof EnvironmentsRoute;
  "/projects": typeof ProjectsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/environments": typeof EnvironmentsRoute;
  "/projects": typeof ProjectsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/environments" | "/projects";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/environments" | "/projects";
  id: "__root__" | "/" | "/environments" | "/projects";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  EnvironmentsRoute: typeof EnvironmentsRoute;
  ProjectsRoute: typeof ProjectsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/environments": {
      id: "/environments";
      path: "/environments";
      fullPath: "/environments";
      preLoaderRoute: typeof EnvironmentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects": {
      id: "/projects";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof ProjectsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  ProjectsRoute: ProjectsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
